version: "3"
services:
  backend:
    image: node:alpine3.17
    container_name: typer-backend-container
    working_dir: /app
    command: npm run dev
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - database

  # PostgreSQL
  database:
    hostname: database
    image: postgres:latest
    container_name: typer-container
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d # Mount directory for initial SQL files


  # React.js Frontend
  frontend:
    image: node:alpine3.17
    container_name: frontend-container
    working_dir: /app
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
